### ISSUE TITLE
is this right Depends() ?

### ISSUE THREAD

**Issue by CharlyJazz** [CharlyJazz/Chat-Firebase-Apache-Camel#12]
https://github.com/CharlyJazz/Chat-Firebase-Apache-Camel/blob/a5a1b649ec679b6b590745e656e8154261c5a0b1/auth-microservice/app/api/v1/login.py#L14

**Comment by aradkdj** [comment]
Yeah, it's the recommended way to do it
https://fastapi.tiangolo.com/tutorial/security/simple-oauth2/#oauth2passwordrequestform

**Comment by CharlyJazz** [comment]
> Yeah, it's the recommended way to do it https://fastapi.tiangolo.com/tutorial/security/simple-oauth2/#oauth2passwordrequestform

 ty
