### ISSUE TITLE
Implement health endpoint

### ISSUE THREAD

**Issue by kike1996luis** [CharlyJazz/Chat-Firebase-Apache-Camel#22]
Create a Health endpoint for all the microservices.

- [ ] Apache Camel server health server should ping Kafka
- [ ] Auth Server should ping postgres
- [ ] Messages Server should ping Cassandra and Kafka

**Comment by CharlyJazz** [comment]
info: https://thoslin.github.io/microservice-health-check-in-kubernetes/
